spring.datasource.url=jdbc:postgresql://localhost/alura_screenmatch2
spring.datasource.username=postgres
spring.datasource.password=One3cch@n
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update